name: Azure Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1

    - name: Deploy to Azure
      run: |
        az webapp deploy --resource-group example-rg --name example-app-service --src-path ./path-to-your-app
